name: meins_modifiers
version: '${project.version}'
main: de.ender.modifiers.Main
api-version: 1.19
depend: [ meins_core ]
authors: [ ender ]
description: enchantment like Main
website: https://github.com/github-dotEXE
commands:
  modifier:
    description: used to put modifiers on items
